apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-grafana
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - plugin:
        configMapRef:
          name: secret-var-plugin-generator
        input:
          parameters:
            secret_vars: ["ingress_host"]
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "3"
      name: prometheus-grafana
      namespace: argocd
    spec:
      source:
        repoURL: 'https://github.com/aledbf/progressivedelivery-masterclass.git'
        targetRevision: main
        path: "gitops/manifests/prometheus-grafana"
        kustomize:
          patches:
          - target:
              kind: Ingress
              name: jaeger
            patch: |-
              - op: replace
                path: spec/hosts/0
                value: prometheus.{{.ingress_host}}                    
      destination:
        namespace: monitoring
        server: 'https://kubernetes.default.svc'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
        syncOptions:
          - CreateNamespace=true
