apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: keptn-lifecycle-toolkit-system
spec:
  ingress:
    enabled: true
    annotations:
          kubernetes.io/ingress.class: nginx    
    hosts:
      - jaeger