apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - argocd-cm.yaml
  - ingress.yaml
patches:
  - target:
      kind: Ingress
      name: argocd
      namespace: argocd
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: argocd.{{ .ingress_host }}
